services:
  php:
    container_name: php
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - '9000:9000'
    volumes:
      - '.:/var/www'
    networks:
      - app-network

  nginx:
    image: 'nginx:alpine'
    container_name: nginx
    ports:
      - '81:80'
    volumes:
      - '.:/var/www'
      - '.docker/etc/nginx/default.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - php
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
