services:
  php:
    container_name: php
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - '9000:9000'
    volumes:
      - '.:/var/www'
    networks:
      - app-network
  nginx:
    image: 'nginx:alpine'
    container_name: nginx
    ports:
      - '81:80'
      - '444:443'
    volumes:
      - '.:/var/www'
      - '.docker/etc/nginx/default.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - php
    restart: unless-stopped
    networks:
      - app-network
#    mysql:
#        image: 'mysql:8.2'
#        container_name: mysql
#        restart: unless-stopped
#        tty: true
#        ports:
#            - '3306:3306'
#        volumes:
#            - '.docker/var/lib/mysql:/var/lib/mysql'
#        environment:
#            MYSQL_DATABASE: 'choquangninh'
#            MYSQL_USER: 'root'
#            MYSQL_PASSWORD: 'HRKEN_HjiwpNye74_qindTYNW_32JKOE'
#            MYSQL_ROOT_PASSWORD: 'HRKEN_HjiwpNye74_qindTYNW_32JKOE'
#        networks:
#            - app-network
#    postgres:
#        image: 'postgres:13'
#        container_name: postgres
#        restart: unless-stopped
#        tty: true
#        ports:
#            - '3306:5432'
#        volumes:
#            - '.docker/var/lib/postgres:/var/lib/postgresql/data'
#        environment:
#            POSTGRES_DB: 'choquangninh'
#            POSTGRES_USER: 'root'
#            POSTGRES_PASSWORD: 'HRKEN_HjiwpNye74_qindTYNW_32JKOE'
#        networks:
#            - app-network
#    mariadb:
#        image: mariadb:10.4.32
#        container_name: mariadb-container
#        restart: always
#        environment:
#            MYSQL_ROOT_PASSWORD: 'HRKEN_HjiwpNye74_qindTYNW_32JKOE'
#            MYSQL_DATABASE: 'choquangninh'
##            MYSQL_USER: your_database_user
##            MYSQL_PASSWORD: your_database_password
#        ports:
#            - "3306:3306"
#        volumes:
#            - .docker/var/lib/mariadb:/var/lib/mysql
##            - mariadb:/var/lib/mysql
##            - type: volume
##              source: .docker/var/lib/mariadb
##              target: /var/lib/mysql
#        networks:
#            - app-network
networks:
  app-network:
    driver: bridge
#volumes:
#    mariadb:
